In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.random.rand(5)

array([0.17111112, 0.62267745, 0.26960491, 0.80059977, 0.48196643])

In [16]:
np.random.rand(3,3)

array([[0.85426937, 0.05200408, 0.8494098 ],
       [0.2673035 , 0.63839743, 0.03540543],
       [0.27793267, 0.34903699, 0.22758966]])

In [17]:
np.random.randn(2)

array([ 2.23874497, -2.82804776])

In [18]:
np.random.randn(4,4)

array([[ 0.30361105, -1.51285234, -1.18432287,  0.56942426],
       [ 0.85168178,  1.49344902,  1.22302666, -1.22437351],
       [-1.07033699,  0.96189503,  0.47725356, -0.66684262],
       [ 0.43523326, -0.26381096, -1.66780107,  0.30170348]])

In [36]:
np.random.randint(1,100,10)

array([66, 78, 89, 89, 40, 19, 94, 39, 12, 76])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
randomarr = np.random.randint(0,50,10)

In [24]:
randomarr 

array([12, 37,  1, 29, 44, 21, 37, 38, 44, 26])

In [25]:
arr.reshape(5,5)  # change the shape of array. reshape()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
randomarr.max()

44

In [27]:
randomarr.min()

1

In [65]:
randomarr.argmax() # max value position 

4

In [29]:
randomarr.argmin()

2

In [31]:
arr.shape

(25,)

In [32]:
arr = arr.reshape(5,5)

In [33]:
arr.shape

(5, 5)

In [34]:
arr.dtype

dtype('int64')

## Numpy Index And Selection  

In [37]:
arr = np.arange(0,11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[8]

8

In [40]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[0:5] = 100 

In [44]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
slice_arr = arr[0:6]

In [46]:
slice_arr

array([100, 100, 100, 100, 100,   5])

In [47]:
slice_arr[:] = 95 

In [48]:
slice_arr

array([95, 95, 95, 95, 95, 95])

In [49]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [50]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
arr_2d[0][0]

5

In [52]:
arr_2d[0]

array([ 5, 10, 15])

In [53]:
arr_2d[2,1]

40

In [54]:
arr_2d[:2,1]

array([10, 25])

In [56]:
arr1 = np.arange(1,11)

In [58]:
bool_arr = arr1 <5 

In [59]:
bool_arr     

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [60]:
arr1[bool_arr]

array([1, 2, 3, 4])

In [61]:
arr1[ arr1<5]

array([1, 2, 3, 4])

In [62]:
arr_2d = np.arange(50).reshape(5,10)

In [63]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:

arr_2d[1:3,3:5] # Select the number you want 

array([[13, 14],
       [23, 24]])

## Numpy Operation 

* Array with Array 
* Array with scalars 
* Universal Array Function

In [69]:
import numpy as np

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [73]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [74]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [76]:
arr/arr # warning value if 0/0

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [77]:
1/arr

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [78]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [79]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [80]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [81]:
np.max(arr)

10

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])